//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TM_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class state
    {
        public long state_id { get; set; }
        public string state_code { get; set; }
        public string state_name { get; set; }
        public long country_id { get; set; }
        public bool is_active { get; set; }
        public bool is_deleted { get; set; }
        public long created_by { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<long> last_modified_by { get; set; }
        public Nullable<System.DateTime> last_modified_date { get; set; }
        public long version { get; set; }
    
        public virtual country country { get; set; }
    }
}
